title: Default

status:
  draft: Draft
  listed: Published

num: '{{ page.datetime.toDate("Ymd") }}'

sections:
  content:
    type: fields
    fields:
      location:
        label: Localisation
        type: text
      datetime:
        width: 1/3
        label: Jour
        type: date

      time:
        width: 1/3
        label: heure
        type: text

      registration:
        width: 1/3
        label: Inscriptions
        type: toggle
        text:
          - Complet
          - Inscriptions ouvertes
        default: true
      information:
        label: Information
        type: writer
        marks:
          - italic
          - link
          - bold
        nodes:
          - paragraph
      ticketing_url:
        width: 1/2
        label: Lien vers la billetterie Infomaniak
        type: url

      files:
        width: 1/2
        label: Fichiers
        type: url
      pdf:
        label: Dépôt d'un fichier
        type: files
        max: 1
