title: Default

status:
  draft: Draft
  listed: Published

num: '{{ page.datetime.toDate("Ymd") }}'

sections:
  content:
    type: fields
    fields:
      location:
        label: Localisation
        type: text
      datetime:
        width: 1/3
        label: Jour
        type: date

      time:
        width: 1/3
        label: heure
        type: text

      registration:
        width: 1/3
        label: Inscriptions
        type: toggle
        text:
          - Complet
          - Inscriptions ouvertes
        default: true
      information:
        label: Information
        type: writer
        marks:
          - italic
          - link
          - bold
        nodes:
          - paragraph
      ticketing_url:
        width: 1/2
        label: Lien vers la billetterie Infomaniak
        type: url

      resource_type_spacer:
        type: gap
        width: 1/2

      resource_type:
        width: 1/2
        label: Type de ressource
        type: select
        options:
          link: Lien
          file: Fichier
        default: link

      files:
        label: Lien vers les ressources
        width: 1/2
        type: url
        when:
          resource_type: link

      pdf:
        label: Dépôt d'un fichier de ressources
        width: 1/2
        type: files
        max: 1
        when:
          resource_type: file
