title: Site

tabs:
  header:
    label: Header
    sections:
      header_fields:
        type: fields
        fields:
          header_title:
            label: Titre header
            type: text
          image_left:
            label: Image gauche
            type: files
            max: 1
            required: true
          image_right:
            label: Image droite
            type: files
            max: 1
            required: true

  intro:
    label: Intro
    sections:
      intro_fields:
        type: fields
        fields:
          intro_text:
            label: Intro
            type: writer
            marks:
              - italic
              - link
            nodes:
              - paragraph
          kickoff_url:
            label: Ressources atelier kick-off
            type: url

  information:
    label: Information
    sections:
      information_fields:
        type: fields
        fields:
          information_title:
            label: Titre
            type: text
          information_blocks:
            label: Information
            type: blocks
            fieldsets:
              writer:
                preview: fields
                wysiwyg: true
                name: Texte
                icon: text
                fields:
                  text:
                    type: writer
                    marks:
                      - italic
                      - link
                    nodes:
                      - paragraph
              cta:
                preview: fields
                wysiwyg: true
                name: CTA
                icon: url
                fields:
                  cta_url:
                    label: Lien ou mail
                    type: text
                  cta_title:
                    label: Titre du bouton
                    type: text

  footer:
    label: Footer
    sections:
      footer_fields:
        type: fields
        fields:
          footer_title:
            label: Titre
            type: text
          footer_content:
            label: Footer
            type: writer
            marks:
              - italic
              - link
              - email
            nodes:
              - paragraph

  pages:
    label: Pages
    sections:
      pages:
        type: pages
